import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 使用文档侧边栏 - 只显示使用文档文件夹内容
  tutorialSidebar: [
    'intro', // 包含intro页面
    {
      type: 'autogenerated',
      dirName: '使用文档',
    }
  ],
  
  // 使用案例侧边栏 - 只显示使用案例文件夹内容
  useCasesSidebar: [
    {
      type: 'autogenerated',
      dirName: '使用案例',
    }
  ],
  
  // 常见问题侧边栏 - 只显示常见问题文件夹内容
  faqSidebar: [
    {
      type: 'autogenerated',
      dirName: '常见问题',
    }
  ],
  
  // 更新日志侧边栏 - 只显示更新日志文件夹内容
  changelogSidebar: [
    {
      type: 'autogenerated',
      dirName: '更新日志',
    }
  ],
};

export default sidebars;
