import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 显示所有内容，最简单的配置
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
